### ISSUE TITLE
Deprication

### ISSUE THREAD

**Issue by ryannel** [JuliaStats/SVM.jl#36]
This library is marked for deprecation. Are there any plans for it's revival?

**Comment by IainNZ** [comment]
No known plans. If you'd like to take over as a maintainer, arrangements could be made to do so.

**Comment by ryannel** [comment]
I'd be happy to pick this up if it helps. Where too from here?

**Comment by IainNZ** [comment]
I'd suggest submitting a pull request that updates the package to support Julia 0.4 and over only, and passes the tests. When you do that, ping me.
